import Head from "next/head";
import MessageSignature from "../app/MessageSignature";
import MintNFT from "../app/MintNFT";
import PoolTracker from "../app/PoolTracker";
import type { NextPage } from "next";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { PROJECT_NAME } from "../app/config";
import { Tab } from "@headlessui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Orbitae App</title>
        <meta name="description" content="Generated by Orbitae" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className="flex font-sans text-white antialiased gradient bg-gradient-to-t from-blue-900 to-slate-900 leading-relaxed tracking-wide">
        <div className="flex flex-grow flex-col max-w-7xl min-h-screen m-auto ">
          <div className="flex items-center p-6">
            <div className="flex justify-start">
              <a href="#">
                <span className="sr-only">Workflow</span>
                <img src="./logo.svg" alt="DApp Logo" className="h-10 w-auto" />
              </a>
            </div>
            <div className="pl-4">
              <p>{PROJECT_NAME}</p>
            </div>
            <div className="flex items-center justify-end ml-auto">
              <ConnectButton label="Connect" />
            </div>
          </div>
          <div className="container mx-auto mb-auto">
            <div className="px-3 lg:px-0">
              <h1 className="my-4 text-2xl md:text-3xl lg:text-5xl font-black leading-tight text-center">
                Welcome to your new DApp!
              </h1>
              <p className="leading-normal text-gray-100 text-base md:text-xl lg:text-2xl mb-8 text-center">
                Take a peek at what you can do right away
              </p>
              <div className="flex w-full flex-col items-center justify-center">
                <Tab.Group>
                  <Tab.List className="flex space-x-1 rounded-xl bg-blue-900/20 p-1 w-full max-w-md mb-3">
                    <Tab
                      className={({ selected }) =>
                        `w-full rounded-lg py-2.5 text-sm font-medium leading-5 ring-white ring-opacity-60 ring-offset-2 ring-offset-blue-400 focus:outline-none focus:ring-2 ${
                          selected
                            ? "bg-blue-500 shadow"
                            : "text-blue-100 hover:bg-white/[0.12] hover:text-white"
                        }`
                      }
                    >
                      Message Signing
                    </Tab>
                    <Tab
                      className={({ selected }) =>
                        `w-full rounded-lg py-2.5 text-sm font-medium leading-5 ring-white ring-opacity-60 ring-offset-2 ring-offset-blue-400 focus:outline-none focus:ring-2 ${
                          selected
                            ? "bg-blue-500 shadow"
                            : "text-blue-100 hover:bg-white/[0.12] hover:text-white"
                        }`
                      }
                    >
                      NFT Minting
                    </Tab>
                    <Tab
                      className={({ selected }) =>
                        `w-full rounded-lg py-2.5 text-sm font-medium leading-5 ring-white ring-opacity-60 ring-offset-2 ring-offset-blue-400 focus:outline-none focus:ring-2 ${
                          selected
                            ? "bg-blue-500 shadow"
                            : "text-blue-100 hover:bg-white/[0.12] hover:text-white"
                        }`
                      }
                    >
                      Event Tracker
                    </Tab>
                  </Tab.List>
                  <div className="w-full">
                    <Tab.Panels>
                      <Tab.Panel>
                        <MessageSignature />
                      </Tab.Panel>
                      <Tab.Panel>
                        <MintNFT />
                      </Tab.Panel>
                      <Tab.Panel>
                        <PoolTracker />
                      </Tab.Panel>
                    </Tab.Panels>
                  </div>
                </Tab.Group>
              </div>
            </div>
          </div>
          <footer>
            <div className="flex w-full mx-auto content-end">
              <div className="p-2 ml-auto">{PROJECT_NAME} &#128640;</div>
            </div>
          </footer>
        </div>
      </div>
    </>
  );
};

export default Home;
